---
- name: "Basic machine setup"
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
  - name: Enable NetworkManager
    become: yes
    systemd:
      no_block: False
      name: NetworkManager
      enabled: True
      state: started
      scope: system

  - name: Update all packages
    become: yes
    pacman:
      update_cache: yes
      upgrade: yes

  - name: Install main packages
    tags: ["apps"]
    become: yes
    pacman:
      state: present
      name:
        - sway
        - termite
        - zsh
        - firefox
        - code
        - xorg-server-xwayland
        - gopass
        - bemenu
        - strace
        - bemenu-wlroots
        - fwupd

  - name: Link .config dotfiles
    tags: ["dotfiles"]
    file:
      src: "{{ item.root }}{{ item.path }}"
      dest: "~/.config/{{ item.path }}"
      state: link
      force: yes
    with_filetree:
      - config/
    when:
      # Only list root-level directories
      - "'/' not in item.path"
      - item.state == "directory"

  - name: Create home config directories and symlink all files
    tags: ["dotfiles"]
    file:
      access_time: preserve
      modification_time: preserve
      src: '{{ (item.state == "file") | ternary(item.root+item.path, "") }}'
      dest: "~/{{ item.path }}"
      state: '{{ (item.state == "file") | ternary("link", "directory") }}'
      force: yes
    with_filetree:
      - home/
