# TODO Copy /etc files
# - pacman.conf
# - makepkg.conf
---
- name: "Basic machine setup"
  hosts: localhost
  gather_facts: no
  connection: local

  roles:
  - kewlfft.aur

  tasks:
  - name: "Configure user: nenad"
    tags: ["user"]
    become: yes
    user:
      name: nenad
      create_home: yes
      group: users
      groups: ["docker", "input", "wheel", "video"]
      shell: /usr/bin/zsh

  - name: "Configure user: nenad-home"
    tags: ["user"]
    become: yes
    user:
      name: nenad-home
      create_home: yes
      group: users
      groups: ["docker", "input", "wheel", "video"]
      shell: /usr/bin/zsh

  - name: Enable NetworkManager
    become: yes
    systemd:
      no_block: False
      name: NetworkManager
      enabled: True
      state: started
      scope: system

  # Has to be done before we install any other package
  - name: Install yay
    tags: ["system"]
    aur:
      state: present
      name:
        - yay

  - name: Update all packages
    tags: ["update"]
    aur:
      upgrade: yes

  - name: Install main packages
    tags: ["apps"]
    aur:
      state: present
      name:
        # Community
        - pavucontrol
        - pulseaudio
        - termite
        - htop
        - zsh
        - firefox
        - code
        - xorg-server-xwayland-git # Until xorg-server-xwayland updates their version
        - gopass
        - bemenu
        - strace
        - bemenu-wlroots
        - fwupd
        - thunderbird
        - alsa-utils
        - light
        - waybar
        - terminus-font-otb
        - otf-font-awesome
        - bc
        - mako
        - playerctl
        - swaylock
        - swayidle
        - dbeaver
        - wl-clipboard
        - pacman-contrib
        - vlc
        - tldr
        - nomacs
        - libva-intel-driver
        - libva-mesa-driver
        - kubectl
        - libnotify
        # AUR
        - sway-git # Migrate to sway once there is a new stable version
        - terminus-font-ttf
        - goland
        - goland-jre
        - phpstorm
        - phpstorm-jre
        - yay
        - zsh-theme-powerlevel10k-git
        - j4-dmenu-desktop
        - slack-desktop
        - activitywatch-bin
        - ydotool
        - oh-my-zsh-git
        - pinentry-wayland
        - firefox-nightly
        - wdisplays

  - name: Link .config dotfiles
    tags: ["dotfiles"]
    file:
      src: "{{ item.root }}{{ item.path }}"
      dest: "~/.config/{{ item.path }}"
      state: link
      force: yes
    with_filetree:
      - config/
    when:
      # Only list root-level directories
      - "'/' not in item.path"
      - item.state == "directory"

  - name: Create home config directories and symlink all files
    tags: ["dotfiles"]
    file:
      access_time: preserve
      modification_time: preserve
      src: '{{ (item.state == "file") | ternary(item.root+item.path, "") }}'
      dest: "~/{{ item.path }}"
      state: '{{ (item.state == "file") | ternary("link", "directory") }}'
      force: yes
    with_filetree:
      - home/
